[features]
seeds = false
skip-lint = false
[programs.devnet]
w3bber_voting = "8xgpGQtTaPPppnnf6iDkUP1zzDsqXfdZgoMG7jUSEwov"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/aashishgarg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
